version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: expense-manager-db
    environment:
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: expense_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U expense_user -d expense_db']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
